<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <!-- This is an example of a URDF. -->
    <!-- As we move through the file, new things to note will be pointed out. -->
    <!-- It's not meant an example of GOOD design, but an example of some of the various features of URDF/xacro. -->



    <!-- This will include all the contents of example_include.xacro first. Go check it out! -->
    <xacro:include filename="bipednav_include.xacro" />

    <!-- Define the body parameters -->
    <xacro:property name="body_height" value="0.6" />
    <xacro:property name="body_thickness" value="0.2" />
    <xacro:property name="body_width" value="0.5" />
    <xacro:property name="thigh_length" value="0.5" />
    <xacro:property name="calf_length" value="0.5" />
    <xacro:property name="leg_radius" value="0.1" />


    <!-- This first link called "world" is empty -->
    <link name="world"></link>

    <joint name="base_joint" type="fixed"> 
        <origin xyz="0 0 ${thigh_length + calf_length + body_height/2} " rpy="0 0 0"/>
        <parent link = "world"/>
        <child link = "base_link"/>
    </joint>


    <!-- <xacro:inertial_box mass="10" x="50" y="20" z="60" link_name="base_link" color="1 0 0 1">
        <origin xyz="0 0 1.35" rpy="0 0 0"/>
    </xacro:inertial_box> -->

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.2 0.5 0.6" />
            </geometry>
            <material name="green">
                <color rgba="0.2 1 0.2 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.2 0.5 0.6" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="12" />
            <inertia ixx="2.26" ixy="0.0" ixz="0.0" iyy="6.26" iyz="0.0" izz="8.5" />
        </inertial>
    </link>

    <joint name="toss_joint_1" type="revolute"> 
        <origin xyz="0 -0.15 ${-body_height/2}" rpy="0 0 0"/>
        <parent link = "base_link"/>
        <child link = "thigh_link_1"/>
        <axis xyz="0 -1 0"/>
        <limit lower="${-pi/3}" upper="${pi/2}" velocity="100" effort="100"/> 
    </joint>

    

    <link name="thigh_link_1">
        <visual>
            <origin xyz="0 0 ${-thigh_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${thigh_length}" radius="${leg_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="0 0 ${-thigh_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${thigh_length}" radius="${leg_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${thigh_length}" radius="${leg_radius}">
            <origin xyz="0 0 ${-thigh_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="toss_joint_2" type="revolute"> 
        <origin xyz="0 0.15 ${-body_height/2}" rpy="0 0 0"/>
        <parent link = "base_link"/>
        <child link = "thigh_link_2"/>
        <axis xyz="0 -1 0"/>
        <limit lower="${-pi/3}" upper="${pi/2}" velocity="100" effort="100"/> 
    </joint>


    <link name="thigh_link_2">
        <visual>
            <origin xyz="0 0 ${-thigh_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${thigh_length}" radius="${leg_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="0 0 ${-thigh_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${thigh_length}" radius="${leg_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${thigh_length}" radius="${leg_radius}">
            <origin xyz="0 0 ${-thigh_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <joint name="knee_joint_1" type="revolute"> 
        <origin xyz="0 0 ${-thigh_length}" rpy="0 0 0"/>
        <parent link = "thigh_link_1"/>
        <child link = "calf_link_1"/>
        <axis xyz="0 -1 0"/>
        <limit lower="${-pi/2}" upper="0" velocity="100" effort="100"/> 
    </joint>

    

    <link name="calf_link_1">
        <visual>
            <origin xyz="0 0 ${-calf_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${calf_length}" radius="${leg_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="0 0 ${-calf_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${calf_length}" radius="${leg_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${calf_length}" radius="${leg_radius}">
            <origin xyz="0 0 ${-calf_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="knee_joint_2" type="revolute"> 
        <origin xyz="0 0 ${-calf_length}" rpy="0 0 0"/>
        <parent link = "thigh_link_2"/>
        <child link = "calf_link_2"/>
        <axis xyz="0 -1 0"/>
        <limit lower="${-pi/2}" upper="0" velocity="100" effort="100"/> 
    </joint>


    <link name="calf_link_2">
        <visual>
            <origin xyz="0 0 ${-calf_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${calf_length}" radius="${leg_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="0 0 ${-calf_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${calf_length}" radius="${leg_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${calf_length}" radius="${leg_radius}">
            <origin xyz="0 0 ${-calf_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <joint name="ankle_joint_1" type="fixed"> 
        <origin xyz="0 0 ${-calf_length}" rpy="0 0 0"/>
        <parent link = "calf_link_1"/>
        <child link = "foot_link_1"/>
    </joint>

    <link name="foot_link_1">
        <visual>
            <origin xyz="0.1 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.4 0.2 0.05" />
            </geometry>
            <material name="green">
                <color rgba="0.2 1 0.2 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.1 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.4 0.2 0.05" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.1 0 0" rpy="0 0 0"/>
            <mass value="12" />
            <inertia ixx="2.26" ixy="0.0" ixz="0.0" iyy="6.26" iyz="0.0" izz="8.5" />
        </inertial>
    </link>

    <joint name="ankle_joint_2" type="fixed"> 
        <origin xyz="0 0 ${-calf_length}" rpy="0 0 0"/>
        <parent link = "calf_link_2"/>
        <child link = "foot_link_2"/>
    </joint>

    <link name="foot_link_2">
        <visual>
            <origin xyz="0.1 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.4 0.2 0.05" />
            </geometry>
            <material name="green">
                <color rgba="0.2 1 0.2 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.1 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.4 0.2 0.05" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.1 0 0" rpy="0 0 0"/>
            <mass value="12" />
            <inertia ixx="2.26" ixy="0.0" ixz="0.0" iyy="6.26" iyz="0.0" izz="8.5" />
        </inertial>
    </link>



    <!-- camera_joint describes where the camera is relative to the arm -->
    <!-- - Even though the camera isn't moving relative to the arm, it will probably be helpful to have its own link/frame rather than just adding more visuals to the arm -->
    <!-- - For this example, the camera_link origin will be at the centre of the camera's "sensor" -->
    <joint name="camera_joint" type="fixed">
        <origin xyz="${body_thickness/2} 0 ${body_height/2}" rpy="0 ${pi/4} 0"/>
        <parent link="base_link"/>
        <child link="camera_link"/>        
    </joint>


    <!-- camera_link describes the camera at the end of the arm -->
    <!-- - It has multiple visual elements, which ultimately get combined together -->
    <!-- - Even if we specify different materials, RViz will just colour them all the same as the first -->
    <!-- - Although we could also specify multiple collision geometries, instead we just use a single box that encompasses the whole camera -->
    <link name="camera_link">
        <visual>
            <origin xyz="-0.03 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.06 0.15 0.15" />
            </geometry>
            <material name="white" />
        </visual>
        <visual>
            <origin xyz="0.03 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder length="0.06" radius="0.04" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="0.0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.12 0.15 0.15" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="0.12" y="0.15" z="0.15">
            <origin xyz="0.0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>




    <xacro:include filename="bipednav_gazebo.xacro" />


</robot>
