function [value,isterminal,direction] = ground_impact(t,in2)
%GROUND_IMPACT
%    [VALUE,ISTERMINAL,DIRECTION] = GROUND_IMPACT(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    15-May-2024 17:12:35

q1 = in2(1,:);
q2 = in2(2,:);
q3 = in2(3,:);
q4 = in2(4,:);
t2 = q1+q2;
t3 = q3+t2;
value = sin(q4+t3)./2.0+sin(q1)./2.0+sin(t2)./2.0+sin(t3)./2.0;
if nargout > 1
    isterminal = 1.0;
end
if nargout > 2
    direction = -1.0;
end
end
