function [value,isterminal,direction] = ground_impact_stick(t,in2)
%GROUND_IMPACT_STICK
%    [VALUE,ISTERMINAL,DIRECTION] = GROUND_IMPACT_STICK(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    11-Feb-2024 22:04:56

q1 = in2(1,:);
q3 = in2(3,:);
t2 = cos(q1);
value = [q3-t2;q3+t2];
if nargout > 1
    isterminal = [1.0;1.0];
end
if nargout > 2
    direction = [-1.0;-1.0];
end
end
